### ISSUE TITLE
Build error on KUbuntu 21.04 (error: could not compile `clap`)

### ISSUE THREAD

**Issue by ppawel** [JojiiOfficial/LiveBudsCli#78]
I installed dependencies (libdbus-dev and cargo), when trying to build with `cargo install earbuds`, I get:

```
   Compiling async-global-executor v2.0.2
   Compiling libpulse-binding v2.25.0
   Compiling async-std v1.10.0
   Compiling clap v3.0.0-beta.4
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/ppawel/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: use of unstable library feature 'osstring_ascii'
   --> /home/ppawel/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/parse/matches/matched_arg.rs:130:19
    |
130 |                 v.eq_ignore_ascii_case(val)
    |                   ^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #70516 <https://github.com/rust-lang/rust/issues/70516> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `earbuds v0.1.9`, intermediate artifacts can be found at `/tmp/cargo-installNS1fmy`

Caused by:
  build failed
```

If I build from local source with `cargo build`, it works.

**Comment by JojiiOfficial** [comment]
Probably `cargo install --locked` will work if you want to use the `install` subcommand. I'll probably have to update some dependencies and create a new release. Thanks for reporting!

**Comment by notrishabh** [comment]
Used cargo install --locked earbuds..


`error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.0.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.1.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.10.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.11.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.12.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.13.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.14.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.15.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.2.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.3.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.4.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.5.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.6.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.7.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.8.rcgu.o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.earbuds.d7ws1vs5-cgu.9.rcgu.o" "-o" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac" "/tmp/cargo-installIcpsd7/release/deps/earbuds-26a91f54891239ac.3juz79vdlmn439uw.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-installIcpsd7/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installIcpsd7/release/deps/libnix-81ea54c4cbdd1181.rlib" "/tmp/cargo-installIcpsd7/release/deps/libmemoffset-19a7f3fa5b036509.rlib" "/tmp/cargo-installIcpsd7/release/deps/libofiles-fe1858f0b64f7229.rlib" "/tmp/cargo-installIcpsd7/release/deps/libglob-de83bedd02b3af32.rlib" "/tmp/cargo-installIcpsd7/release/deps/liberror_chain-02e99b9f3f1d6ab4.rlib" "/tmp/cargo-installIcpsd7/release/deps/libserde_json-bb3c6f74fdd4ba5d.rlib" "/tmp/cargo-installIcpsd7/release/deps/libryu-761e36d9b20e7920.rlib" "/tmp/cargo-installIcpsd7/release/deps/libitoa-c467ed84c607f4bf.rlib" "/tmp/cargo-installIcpsd7/release/deps/libhuman_panic-2adeb32e37302d71.rlib" "/tmp/cargo-installIcpsd7/release/deps/libtoml-d8117c6734393fb4.rlib" "/tmp/cargo-installIcpsd7/release/deps/libos_type-7a60ac9f6f45a03f.rlib" "/tmp/cargo-installIcpsd7/release/deps/libregex-02b09702d365fdc5.rlib" "/tmp/cargo-installIcpsd7/release/deps/libaho_corasick-8659ed2af22de6c0.rlib" "/tmp/cargo-installIcpsd7/release/deps/libregex_syntax-35bb7c472c94dc38.rlib" "/tmp/cargo-installIcpsd7/release/deps/libuuid-99edcc35dc5ac9bd.rlib" "/tmp/cargo-installIcpsd7/release/deps/libgetrandom-740c4a16b3c419c5.rlib" "/tmp/cargo-installIcpsd7/release/deps/libclap_generate-9200c34a28cd27e7.rlib" "/tmp/cargo-installIcpsd7/release/deps/libbluetooth_serial_port_async-f95ee4fa6636aff1.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnix-b87415f628e4fcdd.rlib" "/tmp/cargo-installIcpsd7/release/deps/libmio-5492d0e510fd5572.rlib" "/tmp/cargo-installIcpsd7/release/deps/libiovec-4fe0ca5e9dd6b7b2.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnet2-8cfd0b37849ff827.rlib" "/tmp/cargo-installIcpsd7/release/deps/libenum_primitive-1e33501517dfb9cf.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnum_traits-924f61a6c5ac996b.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnotify_rust-af8e08d19c9ad304.rlib" "/tmp/cargo-installIcpsd7/release/deps/libzbus-0b1f5c87559fb3ba.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures-120297bd8d918735.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_executor-60cebee8f16de687.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_util-ca6bee55cb02f06b.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_channel-925e7b88a781d554.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_sink-89c80310102e3951.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_task-ea678d0e5c9041f8.rlib" "/tmp/cargo-installIcpsd7/release/deps/libpin_utils-45eee4026727bb9f.rlib" "/tmp/cargo-installIcpsd7/release/deps/libscoped_tls-d6d8d7eeaa3bdb15.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnix-4b231f27a94c38b5.rlib" "/tmp/cargo-installIcpsd7/release/deps/libvoid-c3b10a4ff6412aaa.rlib" "/tmp/cargo-installIcpsd7/release/deps/libcfg_if-6b608322be8e315f.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnb_connect-f8fa41c59a0d09e9.rlib" "/tmp/cargo-installIcpsd7/release/deps/libzvariant-97ebd0e6e2e3affa.rlib" "/tmp/cargo-installIcpsd7/release/deps/libenumflags2-8df7a0d2bc25e7cc.rlib" "/tmp/cargo-installIcpsd7/release/deps/libbyteorder-2c22f3b79f938205.rlib" "/tmp/cargo-installIcpsd7/release/deps/libstatic_assertions-f2b028433ee71a15.rlib" "/tmp/cargo-installIcpsd7/release/deps/libserde-2d8a7fbddd35a486.rlib" "/tmp/cargo-installIcpsd7/release/deps/libmpris-cf4b31734757aadf.rlib" "/tmp/cargo-installIcpsd7/release/deps/libdbus-132d704cebff2400.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfrom_variants-f0994751de628ef9.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfailure-ec04e40c24083ede.rlib" "/tmp/cargo-installIcpsd7/release/deps/libbacktrace-05976c130b7c0792.rlib" "/tmp/cargo-installIcpsd7/release/deps/libminiz_oxide-67ccad7c8d263aad.rlib" "/tmp/cargo-installIcpsd7/release/deps/libadler-577ab357c72558c4.rlib" "/tmp/cargo-installIcpsd7/release/deps/libobject-0fdd642a537c8bdf.rlib" "/tmp/cargo-installIcpsd7/release/deps/libaddr2line-a2761b13102b4f65.rlib" "/tmp/cargo-installIcpsd7/release/deps/libgimli-fbbdaf5cdd9b84ad.rlib" "/tmp/cargo-installIcpsd7/release/deps/librustc_demangle-3ceada855617d87a.rlib" "/tmp/cargo-installIcpsd7/release/deps/libpulsectl-7be6a2ad81d267ab.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblibpulse_binding-d72c5bb7434c3ed0.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblibpulse_sys-452f5f76a940340e.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnum_traits-1856dfc6f59a4323.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_std-ab17a53be08151b7.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_global_executor-89e72c3161b5b560.rlib" "/tmp/cargo-installIcpsd7/release/deps/libblocking-09792534322ca1f7.rlib" "/tmp/cargo-installIcpsd7/release/deps/libatomic_waker-83c0775e20b24d10.rlib" "/tmp/cargo-installIcpsd7/release/deps/libnum_cpus-5107eeb963e56a54.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_mutex-8f9231d9c648f99e.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_executor-52afa8670a355984.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_task-5e09a314f189f8ac.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_io-557a28def8e14125.rlib" "/tmp/cargo-installIcpsd7/release/deps/libslab-36c1471741c92761.rlib" "/tmp/cargo-installIcpsd7/release/deps/libpolling-7001ed224c612ae6.rlib" "/tmp/cargo-installIcpsd7/release/deps/libonce_cell-e5d55c0b25d789c5.rlib" "/tmp/cargo-installIcpsd7/release/deps/libsocket2-018667aefc6c990a.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_lite-5bf27945bffdf849.rlib" "/tmp/cargo-installIcpsd7/release/deps/libmemchr-05648a496e8cb255.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfastrand-7c3688f7c8686b31.rlib" "/tmp/cargo-installIcpsd7/release/deps/libwaker_fn-6cb08d9b81def22c.rlib" "/tmp/cargo-installIcpsd7/release/deps/libparking-f0d76832de0ac630.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_io-6a0471656e648784.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_channel-492e82c1edb57fd4.rlib" "/tmp/cargo-installIcpsd7/release/deps/libconcurrent_queue-52fc3b398ca2a4fe.rlib" "/tmp/cargo-installIcpsd7/release/deps/libcache_padded-7e4f96600caafc3f.rlib" "/tmp/cargo-installIcpsd7/release/deps/libasync_lock-2ddd40c580ad0b86.rlib" "/tmp/cargo-installIcpsd7/release/deps/libevent_listener-f75b067f06876f1b.rlib" "/tmp/cargo-installIcpsd7/release/deps/libpin_project_lite-152165e941060223.rlib" "/tmp/cargo-installIcpsd7/release/deps/libfutures_core-b13bd27766f62180.rlib" "/tmp/cargo-installIcpsd7/release/deps/libkv_log_macro-863e70ee2de782a1.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblog-5f084407ed2404df.rlib" "/tmp/cargo-installIcpsd7/release/deps/libvalue_bag-23d99e2eea4a357b.rlib" "/tmp/cargo-installIcpsd7/release/deps/libcfg_if-7e32e7654926b70b.rlib" "/tmp/cargo-installIcpsd7/release/deps/libgalaxy_buds_rs-b86e97fe10ac4bcb.rlib" "/tmp/cargo-installIcpsd7/release/deps/libblurz-de90079c858450e6.rlib" "/tmp/cargo-installIcpsd7/release/deps/libhex-2bf3921f57768a2a.rlib" "/tmp/cargo-installIcpsd7/release/deps/libdbus-acaa9754813f9902.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblibdbus_sys-e0f71985cc16cbfb.rlib" "/tmp/cargo-installIcpsd7/release/deps/libclap-5a705785e2c3a6d6.rlib" "/tmp/cargo-installIcpsd7/release/deps/libstrsim-a72f0404a40f3220.rlib" "/tmp/cargo-installIcpsd7/release/deps/libatty-3901b3fbbec047b0.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblibc-ad97a37c091d02e2.rlib" "/tmp/cargo-installIcpsd7/release/deps/libtextwrap-853b108206acb7c9.rlib" "/tmp/cargo-installIcpsd7/release/deps/libvec_map-54b4babd318fd35d.rlib" "/tmp/cargo-installIcpsd7/release/deps/libos_str_bytes-84599ac0dc5fe226.rlib" "/tmp/cargo-installIcpsd7/release/deps/libtermcolor-d8c73027cb9fad55.rlib" "/tmp/cargo-installIcpsd7/release/deps/libunicode_width-d372a33abf9815a1.rlib" "/tmp/cargo-installIcpsd7/release/deps/libindexmap-8dd5b6db6418a098.rlib" "/tmp/cargo-installIcpsd7/release/deps/libhashbrown-d5b388d2e356eaf9.rlib" "/tmp/cargo-installIcpsd7/release/deps/libbitflags-802c3a44ad93282a.rlib" "/tmp/cargo-installIcpsd7/release/deps/liblazy_static-d2c3a447b7f1353c.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-522c175df7e65c76.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6de0d9a99fa442f6.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-acc51f402ffb0a47.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-cbf21249c0bb64a3.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-7811673bd6c230a1.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-9d24c50c56b501a5.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-f2bf86d8579f7abb.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-a510913c7a93022a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-113eb81ce98dbb76.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-36a8ba3e35050b5b.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-6ec306849e1e0cbe.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-cb42b322cd006390.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-598bd3c8385c4a71.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-dcf076dc617ac8b6.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-9231e3c18aac66ef.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-fb02ea9686597718.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f203df3b7c648201.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b0414f7c79a0b9b4.rlib" "-Wl,-Bdynamic" "-lbluetooth" "-lbluetooth" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-l:libpulse.so.0" "-ldbus-1" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lbluetooth
          /usr/bin/ld: cannot find -lbluetooth
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: failed to compile `earbuds v0.1.9`, intermediate artifacts can be found at `/tmp/cargo-installIcpsd7`

Caused by:
  could not compile `earbuds``

**Comment by JojiiOfficial** [comment]
@notrishabh this is a different issue.
